### ISSUE TITLE
【依頼】フリマアプリ挙動確認

### ISSUE THREAD

**Issue by Tomogit2** [Tomogit2/furima-40768#21]
・フリマアプリのURL
https://furima-40768.onrender.com/

・出品者用のメールアドレスとパスワード
ttttttttt1@ttttt.com
tttttt1

・購入者用のメールアドレスとパスワード
ttttttttt2@ttttt.com
tttttt2

**Comment by mayumiasio** [comment]
@Tomogit2 さんご提出ありがとうございます‼︎
動作の確認をしたところ、修正していただきたい箇所がございました。
以下のご確認をお願いします！

[修正依頼箇所]
商品購入機能の実装
クレジットカード情報の入力ができません。


修正が完了しましたら、一度ご自身の本番環境で正しく動作しているか確認してみましょう！
修正内容が反映されていることを確認できましたら以下の最終課題完了報告フォームのご提出をお願いします！
※新しいissueを作っていただく必要はございません。
※質問等でコメントした場合も都度フォームのご提出をお願いします。

https://forms.gle/dYuR1wjeHepbEhU7A

**Comment by Tomogit2** [comment]
大変失礼いたしました。
本番環境でも正しく動作していることが確認できました。
再度よろしくお願いいたします。

**Comment by mayumiasio** [comment]
@Tomogit2 さん、ご提出ありがとうございます!!

動作の確認をしたところ、修正していただきたい箇所がございました。
以下のご確認をお願いします!

[修正依頼箇所]

**商品購入機能の確認**
- [x] **配送先の情報として、郵便番号・都道府県・市区町村・番地・電話番号が必須であること**
- [x] **建物名は任意であること**
都道府県の入力が必須となりますが、入力しなくても商品購入することができてしまいます。
また、他の必須箇所も併せてご確認ください。

<img width="547" alt="スクリーンショット 2024-07-20 12 50 34" src="https://github.com/user-attachments/assets/c909fa5d-c450-4d39-acbd-8390534b1ca3">

修正が完了しましたら、一度ご自身の本番環境で正しく動作しているか確認してみましょう。
修正内容が反映されていることが確認できましたら、再度以下の最終課題完了報告フォームのご提出をお願いします!
※新しいissueを作っていただく必要はございません。
※質問等でコメントした場合も都度フォームのご提出をお願いします。
https://forms.gle/dYuR1wjeHepbEhU7A

**Comment by Tomogit2** [comment]
大変失礼いたしました。
何度もお手数をおかけして、申し訳ございません。
本番環境でも修正内容が反映され、正しく動作していることが確認できました。
再度よろしくお願いいたします。

**Comment by shodai-ito** [comment]
@Tomogit2 さん、最終課題「FURIMA」の開発、お疲れ様です！

ご提出いただいたアプリケーションについて、正常に動作することを確認いたしました。
達成要件を満たしましたので、完了認定（LGTM）とさせていただきます。おめでとうございます！

_※ スタッフ側で実施した動作確認は必須機能についてのみです。追加機能についての動作確認は実施しておりません。追加機能を実装した場合は想定通りの挙動となっているか自分自身で確認をお願い致します。_
_※ Github上の最終課題の履歴はここまで頑張ってきたことの証となります。削除せず大切に保管するようにしましょう。_

![lgtm_01](https://user-images.githubusercontent.com/54050089/186354234-2de2a3d1-500d-4164-81d5-7585cdd03227.png)
